### ISSUE TITLE
Can't clone repo to GitHub Desktop after forking

### ISSUE THREAD

**Issue by jamisoncrawford** [DS4PS/dp4ss-textbook#1]
@lecy I'm not sure why I can't clone it. This is the notification that pops up:

![image](https://user-images.githubusercontent.com/15643196/63120670-bb3b9f80-bf70-11e9-8de8-07fc3e51fb30.png)

I'm hesitant to upload directly to the Master branch.

Thoughts? (Sorry, I'm familiar with GH, but collabs are still very new to me!).

**Comment by lecy** [comment]
Weird.

Just like R Studio requires a base installation of R, GitHub desktop requires a base installation of Git. It looks like maybe it can't find the Git app (which should install automatically with GitHub desktop). 

Maybe restart and try again? Javascript suggests something interface related...
