### ISSUE TITLE
Issues in Week 3 Building Custom Graphics reading

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/dp4ss-textbook#3]
1. In section 1.3.7 Highlighting Groups, the sentence "Perhaps we have a theory that corn-fed players that grew up in Iowa" just stops. I think this is suppose to have some explanation of highlighting players from IOWA.

2. In section 1.4 Highlighting Cases the carriage return is shown in the text as "". It should show the "\n", right?

3. In a few places there is a call to pander:

```
%>% pander()
```
The statement isn't needed and doesn't execute if you have not loaded the library.

**Comment by lecy** [comment]
thanks for these!
