### ISSUE TITLE
p-062-customized-graphics.rmd edits

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/dp4ss-textbook#5]
Hi @lecy!

I was working through the lecture on [custom graphics](http://ds4ps.org/dp4ss-textbook/p-062-customized-graphics.html) and noticed that the Lahman package does not have the object `Master` as it is now called `People`. I worked through the code to update this. You might check the way I did it. Rather than find and replace `Master` with `People`, I just defined the object `Master <- People`. 

Figured I would let you know in case you don't like the way it is set up.

**Comment by jacobtnyoung** [comment]
@lecy actually, it might be easier to just reject all my changes. Then, go through and do a find and replace for 'Master' with 'People'.

**Comment by lecy** [comment]
Got it - seems pretty minor - I'll try and update that when we revise the chapter. The fix works in the meantime. 

I agree - the use of Master instead of People might be confusing to some people, especially once they get to the lab.
